### PR TITLE
<docs> : <Added API Documentation> issue #24

### PR DESCRIPTION
**Pull request by AshwinSriram11**
I have updated Readme file by adding API documentation about different routes.

### CODE REVIEW

**Review by chandansgowda — CHANGES_REQUESTED** [review]
@AshwinSriram11 Need few changes:
1. Add request format
2. For Successful responses the status code will be there (you have put it as None)
3. Refer #34 and make necessary changes in the docs too

**Comment by chandansgowda** [comment]
@AshwinSriram11 Just mention that we will have to pass Appwrite JWT token in the request as auth header

**Comment by AshwinSriram11** [comment]
@chandansgowda I made the changes please tell me if I did any mistake?

**Review by chandansgowda — CHANGES_REQUESTED** [review]

**Comment by AshwinSriram11** [comment]
I added the change @chandansgowda

**Review by chandansgowda — APPROVED** [review]
Good job @AshwinSriram11 
@jddeep Please merge it as one commit.

**Comment by AshwinSriram11** [comment]
Thank you @chandansgowda

**Comment by chandansgowda** [comment]
@AshwinSriram11  Please resolve conflicts

**Comment by AshwinSriram11** [comment]
@chandansgowda I have resolved the changes

**Pull request closed without merging**
