### PR TITLE
feat: add database cleanup function

### LINKED ISSUE #43: Cloud function to delete inactive rooms and active pair chats
Sometime due to some inconsistency, the room might be still available on the database even if no one is in the room. Let's delete these using a scheduled cloud function.

### PR DESCRIPTION
**Pull request by ShamanthOP**
Closes #43 

Added a function to remove stale documents from participants and active_pairs collection. It is scheduled to run everyday at 1:00 A.M. 

Participant documents which do not have a corresponding active room and Active_pair documents older than a day gets removed by the function.

### CODE REVIEW

**Comment by chandansgowda** [comment]
Can we schedule it to run each and every hour or so ? Will there be any issues ? Also, @Aarush-Acharya does this cause any conflict to the discussions feature you are implementing ?

**Comment by ShamanthOP** [comment]
> Can we schedule it to run each and every hour or so ? Will there be any issues ? Also, @Aarush-Acharya does this cause any conflict to the discussions feature you are implementing ?

We can but it wouldn't add any significant benifits. Since it's a background task performance isn't an issue. So executing it once a day seems right.

**Comment by ShamanthOP** [comment]
> @ShamanthOP If we dont do it frequently, inactive rooms will be displayed along with other rooms and users might be trying to join those.

Inactive rooms should be cleared up by the webhook receiver. We can add it here also to be super extra careful though. This PR currently only cleans participants and active_pairs collection.

**Comment by Aarush-Acharya** [comment]
hey @ShamanthOP, I believe we already have a database cleanUp function, and this PR seems to be out of context now

Thank you for your time

**Pull request closed without merging**
